# Generated by Django 4.2.2 on 2023-08-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetdelivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlystationexport',
            name='total_volume',
            field=models.FloatField(default=0),
        ),
    ]
