# Generated by Django 4.2 on 2023-06-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetdelivery', '0002_alter_transportation_ratte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlydistanceprice',
            name='year',
            field=models.IntegerField(default=2023, unique=True),
        ),
        migrations.AlterField(
            model_name='yearlygascharge',
            name='year',
            field=models.IntegerField(default=2023, unique=True),
        ),
        migrations.AlterField(
            model_name='yearlyhillstationdistance',
            name='year',
            field=models.IntegerField(default=2023, unique=True),
        ),
        migrations.AlterField(
            model_name='yearlystationexport',
            name='year',
            field=models.IntegerField(default=2023, unique=True),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
