# Generated by Django 4.2 on 2023-06-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetdelivery', '0005_remove_yearlyhillstationdistance_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlydistanceprice',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='yearlyhillstationdistance',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='yearlystationexport',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
