# Generated by Django 4.2 on 2023-06-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetdelivery', '0006_alter_yearlydistanceprice_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='density',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportation',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transportation',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
