# Generated by Django 4.2 on 2023-06-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beetdelivery', '0007_transportation_density_transportation_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='density',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='price',
        ),
    ]
