# Generated by Django 4.2 on 2023-06-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetdelivery', '0008_remove_transportation_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='container_size',
            field=models.IntegerField(),
        ),
    ]
