# Generated by Django 4.2.2 on 2023-07-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beetdelivery', '0009_alter_schedule_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hill',
            name='location',
        ),
    ]
